export const GET_COMMENT_REQUEST  ='GET_COMMENT_REQUEST '
export const GET_COMMENT_SUCCESS  ='GET_COMMENT_SUCCESS'
export const GET_COMMENT_FAIL  ='GET_COMMENT_FAIL'
export const GET_COMMENT_RESET = 'GET_COMMENT_RESET'
export const AUGMENTE_SKIP_GET_COMMENT = 'AUGMENTE_SKIP_GET_COMMENT'




export const CREATE_COMMENT_REQUEST  ='CREATE_COMMENT_REQUEST '
export const CREATE_COMMENT_SUCCESS  ='CREATE_COMMENT_SUCCESS'
export const CREATE_COMMENT_FAIL  ='CREATE_COMMENT_FAIL'

export const GET_REPLY_COMMENT_REQUEST  ='GET_REPLY_COMMENT_REQUEST '
export const GET_REPLY_COMMENT_SUCCESS  ='GET_REPLY_COMMENT_SUCCESS'
export const GET_REPLY_COMMENT_FAIL  ='GET_REPLY_COMMENT_FAIL'
export const GET_REPLY_COMMENT_RESET = 'GET_REPLY_COMMENT_RESET'


export const COUNT_COMMENT_OF_POST_REQUEST="COUNT_COMMENT_OF_POST_REQUEST"  
export const COUNT_COMMENT_OF_POST_SUCCESS="COUNT_COMMENT_OF_POST_SUCCESS"  
export const COUNT_COMMENT_OF_POST_FAIL="COUNT_COMMENT_OF_POST_FAIL"  




export const COMMENT_STATISTIC_REQUEST = "COMMENT_STATISTIC_REQUEST"
export const COMMENT_STATISTIC_SUCCESS = "COMMENT_STATISTIC_SUCCESS"
export const COMMENT_STATISTIC_FAIL = "COMMENT_STATISTIC_FAIL"



// Sync

export const SET_COMMENT_REPLY = 'SET_COMMENT_REPLY'
export const ADJUST_COMMENT_REPLY = "ADJUST_COMMENT_REPLY"
export const RESET_SYNC_COMMENT_STATE = 'RESET_SYNC_COMMENT_STATE'