export const CREATE_POST_REQUEST  ='CREATE_POST_REQUEST '
export const CREATE_POST_SUCCES  ='CREATE_POST_SUCCESS'
export const CREATE_POST_FAIL  ='CREATE_POST_FAIL'


export const GET_POST_REQUEST  ='GET_POST_REQUEST '
export const GET_POST_SUCCES  ='GET_POST_SUCCESS'
export const GET_POST_FAIL  ='GET_POST_FAIL'