export const CREATE_REACTION_REQUEST  ='CREATE_REACTION_REQUEST '
export const CREATE_REACTION_SUCCESS  ='CREATE_REACTION_SUCCESS'
export const CREATE_REACTION_FAIL  ='CREATE_REACTION_FAIL'


export const GET_REACTION_REQUEST  ='GET_REACTION_REQUEST '
export const GET_REACTION_SUCCESS  ='GET_REACTION_SUCCESS'
export const GET_REACTION_FAIL  ='GET_REACTION_FAIL'



export const UPDATE_REACTION_REQUEST  ='UPDATE_REACTION_REQUEST '
export const UPDATE_REACTION_SUCCESS  ='UPDATE_REACTION_SUCCESS'
export const UPDATE_REACTION_FAIL  ='UPDATE_REACTION_FAIL'

export const DELETE_REACTION_REQUEST  ='DELETE_REACTION_REQUEST '
export const DELETE_REACTION_SUCCESS  ='DELETE_REACTION_SUCCESS'
export const DELETE_REACTION_FAIL  ='DELETE_REACTION_FAIL'

