// Async
export const CREATE_STATUS_REQUEST = 'CREATE_STATUS_REQUEST'
export const CREATE_STATUS_SUCCESS = 'CREATE_STATUS_SUCCESS'
export const CREATE_STATUS_FAIL = 'CREATE_STATUS_FAIL'

export const GET_STATUS_REQUEST = 'GET_STATUS_REQUEST'
export const GET_STATUS_SUCCESS = 'GET_STATUS_SUCCESS'
export const GET_STATUS_FAIL = 'GET_STATUS_FAIL'
export const ADJUST_STATUS_BY_SOCKET = 'ADJUST_STATUS_BY_SOCKET'

export const GET_MY_STATUS_REQUEST = 'GET_MY_STATUS_REQUEST'
export const GET_MY_STATUS_SUCCESS = 'GET_MY_STATUS_SUCCESS'
export const GET_MY_STATUS_FAIL = 'GET_MY_STATUS_FAIL'

export const GET_STATUS_VIEWERS_REQUEST= 'GET_STATUS_VIEWERS_REQUEST'
export const GET_STATUS_VIEWERS_SUCCESS = 'GET_STATUS_VIEWERS_SUCCESS'
export const GET_STATUS_VIEWERS_FAIL = 'GET_STATUS_VIEWERS_FAIL'


export const SEND_STATUS_SEEN_REQUEST= 'SEND_STATUS_SEEN_REQUEST'
export const SEND_STATUS_SEEN_SUCCESS= 'SEND_STATUS_SEEN_SUCCESS'
export const SEND_STATUS_SEEN_FAIL= 'SEND_STATUS_SEEN_FAIL'







// Sync
export const CHOOSE_STATUS_TYPE = 'CHOOSE_STATUS_TYPE'
export const SET_STATUS_CONTENT = 'SET_STATUS_CONTENT'
export const SET_STATUS_IMAGE= 'SET_STATUS_IMAGE'
export const SET_STATUS_AUDIO= 'SET_STATUS_AUDIO'


export const SET_CHOOSE_STORY = 'SET_CHOOSE_STORY'
export const SET_SAME_STORY_INDEX = 'SET_SAME_STORY_INDEX'
export const SET_SAME_STORY_WIDTH = 'SET_SAME_STORY_WIDTH'